### ISSUE TITLE
Add testing for multiple versions of GHC in Travis

### ISSUE THREAD

**Issue by FranklinChen** [music-suite/lilypond#5]
I suggest using https://github.com/hvr/multi-ghc-travis to ensure builds on multiple versions of GHC.

**Comment by hanshoglund** [comment]
Thanks, I'll consider it in the future. Only the current Haskell Platform version is supported at the moment due to time constraints. Patches welcome as always.

Best,
Hans

**Comment by hanshoglund** [comment]
Nice, merged!
