### ISSUE TITLE
lilypond parser, anyone?

### ISSUE THREAD

**Issue by jwaldmann** [music-suite/lilypond#7]
How hard would it be to build a parser for lilypond? I have a use case, and I could look into this.
Is there already a data type that represents "lilypond file contents" 
(with \version , \header, \paper, \score, and it could also contain macro definitions)?

**Comment by hanshoglund** [comment]
There is no datatype for the full files. It should be easy to add a basic expression parser i.e. for things like `c''2 <<c e\staccato>> | << { e2 f } { c2 <<b d>> } >>`. I can give you some pointers in case you want to have a go at it. PRs always welcome.

**Comment by hanshoglund** [comment]
This repo has been merged into: https://github.com/music-suite/music-suite

Will close this :)
