### ISSUE TITLE
Not implemented functions in the `IO` module

### ISSUE THREAD

**Issue by meditans** [music-suite/lilypond#8]
Is there a particular reason for the function in `Data.Music.Lilypond.IO` not to be implemented? It seems to me that that's the most common use case for the lilypond representation.

**Comment by hanshoglund** [comment]
Historical mistake, I ended up duplicating their use in `music-score` and never moved the code over to the `lilypond` package. I'll either do that or remove them before the next release.

**Comment by meditans** [comment]
Ok, that sounds good! Those are very useful functions, and I think a user, seeing the structure of the library, would expect to find them under the `Lilypond` hierarchy.

If you want, I can prepare a PR moving them to `Lilypond`

**Comment by hanshoglund** [comment]
Feel free. I am currently writing up a longer reply on one of the other issues... :)

**Comment by hanshoglund** [comment]
This repo has been merged into: https://github.com/music-suite/music-suite where these functions have been replaced by a single top-level IO function.

Closing :)
